services:
  - type: web
    name: nse-eod-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DB_PATH
        value: "nse_eod_data.db"